### ISSUE TITLE
企業協賛は締め切ったことを明記する

### ISSUE THREAD

**Issue by nabe98** [CompPhysSchool/homepage2025#6]
今の[協賛ページ]( https://compphysschool.github.io/homepage2025/subjects.html )を見るとまだ企業協賛を受け付けているような印象を受ける．
締め切っているなら赤太字で周知すべき．

**Comment by CompPhysSchool** [comment]
preブランチのkyousan.htmlの「本年度の企業協賛の受付は終了いたしました。来年度のご検討をお願い申し上げます。」を赤字にしました。
